Feature(RA-37): Fix develop CI

diff --git a/.github/workflows/ci-develop.yml b/.github/workflows/ci-develop.yml
--- a/.github/workflows/ci-develop.yml
+++ b/.github/workflows/ci-develop.yml
@@ -5,7 +5,6 @@ on:
     branches:
       - "develop"
 
-
 jobs:
   unit-tests:
     runs-on: ubuntu-latest
@@ -32,42 +31,52 @@ jobs:
         run: |
           echo "${{ secrets.KEYSTORE_FILE_BASE64 }}" | base64 -d > app/rebonnte-release-key.jks
           ls -la app/ 
+      
 
+      #start emulator and run instrumented tests
+      - name: Enable KVM
+        run: |
+          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
+          sudo udevadm control --reload-rules
+          sudo udevadm trigger --name-match=kvm
+
+      # Step : Récupérer l'historique Git complet pour SonarCloud
+      - name: Fetch full Git history
+        run: git fetch --unshallow
 
       # Step 4 : Installation des dépendances du projet
       - name: Download dependencies
         run: ./gradlew dependencies
-          
-          # Step  : Lancer les tests unitaire  + jacocoreport 
-      - name: Run Tests/generate Jacoco cover report
+
+      # Step  : Lancer les tests unitaire et instrumented + jacocoreport + sonar analyse
+      - name: Run Tests/generate Jacoco cover report and Sonar Quality Gate analyse
         env:
-           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         uses: reactivecircus/android-emulator-runner@v2
         with:
           target: google_apis
           arch: x86_64
           api-level: 35
           script: |
-           echo "--- [Waiting for emulator to stabilize...]"
-           #sleep 30 
-           adb wait-for-device
-           
-           echo "--- [Unlocking emulator screen...]"
-           adb shell input keyevent 82
-           adb shell wm dismiss-keyguard
-           
-           echo "--- [Lint debug]"
-           ./gradlew lintDebug
-           
-           echo "--- [Generating Jacoco report...]"
-           ./gradlew jacocoReport
-           
-           echo "--- [Checking if Jacoco report exists...]"
-           ls app/build/reports/jacoco/jacocoTestReport
-           cat app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml || echo " [X] - Jacoco report not found"
+            echo "--- [Waiting for emulator to stabilize...]"
+            #sleep 30 
+            adb wait-for-device
+            
+            echo "--- [Unlocking emulator screen...]"
+            adb shell input keyevent 82
+            adb shell wm dismiss-keyguard
+            
+            echo "--- [Lint debug]"
+            ./gradlew lintDebug
+            
+            echo "--- [Generating Jacoco report...]"
+            ./gradlew jacocoReport
+            
+            echo "--- [Checking if Jacoco report exists...]"
+            ls app/build/reports/jacoco/jacocoTestReport
+            cat app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml || echo " [X] - Jacoco report not found"
 
-
-      # Step 6 : Vérification du statut du job
-      - name: Fail PR on error
+      # Step  : No Validation PR en cas d'échec
+      - name: Clearance PR
         if: ${{ failure() }}
-        run: exit 1
+        run: echo "Build ou analyse de qualité échouée, PR bloquée."
