Feature(RA-37): fix indentation error on epic CI .

diff --git a/.github/workflows/ci-epic.yml b/.github/workflows/ci-epic.yml
--- a/.github/workflows/ci-epic.yml
+++ b/.github/workflows/ci-epic.yml
@@ -38,34 +38,33 @@ jobs:
       - name: Download dependencies
         run: ./gradlew dependencies
           
-          # Step  : Lancer les tests unitaire  + jacocoreport 
-               - name: Run Tests/generate Jacoco cover report
-               env:
-                 SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-               uses: reactivecircus/android-emulator-runner@v2
-               with:
-                 target: google_apis
-                 arch: x86_64
-                 api-level: 35
-                 script: |
-                   echo "--- [Waiting for emulator to stabilize...]"
-                   #sleep 30 
-                   adb wait-for-device
-                   
-                   echo "--- [Unlocking emulator screen...]"
-                   adb shell input keyevent 82
-                   adb shell wm dismiss-keyguard
-                   
-                   echo "--- [Lint debug]"
-                   ./gradlew lintDebug
-                   
-                   echo "--- [Generating Jacoco report...]"
-                   ./gradlew jacocoReport
-                   
-                   echo "--- [Checking if Jacoco report exists...]"
-                   ls app/build/reports/jacoco/jacocoTestReport
-                   cat app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml || echo " [X] - Jacoco report not found"
-                   
+# Step  : Lancer les tests unitaire  + jacocoreport
+      - name: Run Tests/generate Jacoco cover report
+        env:
+         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        uses: reactivecircus/android-emulator-runner@v2
+        with:
+         target: google_apis
+         arch: x86_64
+         api-level: 35
+         script: |
+           echo "--- [Waiting for emulator to stabilize...]"
+           #sleep 30 
+           adb wait-for-device
+           
+           echo "--- [Unlocking emulator screen...]"
+           adb shell input keyevent 82
+           adb shell wm dismiss-keyguard
+           
+           echo "--- [Lint debug]"
+           ./gradlew lintDebug
+           
+           echo "--- [Generating Jacoco report...]"
+           ./gradlew jacocoReport
+           
+           echo "--- [Checking if Jacoco report exists...]"
+           ls app/build/reports/jacoco/jacocoTestReport
+           cat app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml || echo " [X] - Jacoco report not found"
 
       # Step 6 : Vérification du statut du job
       - name: Fail PR on error
