feature(RA-38): Upgrade the CI for the PR from Develop to main, now jacoco report and sonar are integrated and the build release is generated.

diff --git a/.github/workflows/ci-main.yml b/.github/workflows/ci-main.yml
--- a/.github/workflows/ci-main.yml
+++ b/.github/workflows/ci-main.yml
@@ -1,5 +1,6 @@
 name: CI - Main Branch PR
 
+
 on:
   pull_request:
     branches:
@@ -7,6 +8,7 @@ on:
     paths:
       - "develop/**"
     types: [opened, synchronize, reopened]
+
 
 jobs:
   unit-tests:
@@ -29,6 +31,13 @@ jobs:
       - name: Make gradlew executable
         run: chmod +x ./gradlew
 
+      # Step 4 : Reconstruire le fichier keystore à partir du secret
+      - name: Decode keystore file
+        run: |
+          echo "${{ secrets.KEYSTORE_FILE_BASE64 }}" | base64 -d > app/rebonnte-release-key.jks
+          ls -la app/ 
+        
+
       #start emulator and run instrumented tests
       - name: Enable KVM
         run: |
@@ -44,30 +53,53 @@ jobs:
       - name: Download dependencies
         run: ./gradlew dependencies
 
-      # Step 5 : Exécuter les tests unitaires
-      - name: Run Unit Tests
-        run: ./gradlew test
-
-      # Step 6 : Démarrer l'émulateur et exécuter les tests instrumentés
-      - name: Start emulator and run instrumented tests
+      # Step  : Lancer les tests unitaire et instrumented + jacocoreport + sonar analyse
+      - name: Run Tests/generate Jacoco cover report and Sonar Quality Gate analyse
+        env:
+         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         uses: reactivecircus/android-emulator-runner@v2
         with:
-          target: google_apis
-          arch: x86_64
-          api-level: 35
-          script: |
-            echo "--- [Waiting for emulator to stabilize...]"
-            adb wait-for-device
-            
-            echo "--- [Unlocking emulator screen...]"
-            adb shell input keyevent 82
-            adb shell wm dismiss-keyguard
-            echo "--- [Building app ...]"
-            ./gradlew build
-            echo "--- [Running instrumented tests ...]"
-            ./gradlew connectedAndroidTest
+           target: google_apis
+           arch: x86_64
+           api-level: 35
+           script: |
+             echo "--- [Waiting for emulator to stabilize...]"
+             #sleep 30 
+             adb wait-for-device
+             
+             echo "--- [Unlocking emulator screen...]"
+             adb shell input keyevent 82
+             adb shell wm dismiss-keyguard
+             
+             echo "--- [Lint debug]"
+             ./gradlew lintDebug
+             
+             echo "--- [Generating Jacoco report...]"
+             ./gradlew jacocoReport
+             
+             echo "--- [Checking if Jacoco report exists...]"
+             ls app/build/reports/jacoco/jacocoTestReport
+             cat app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml || echo " [X] - Jacoco report not found"
+             
+             echo "--- [SonarCloud Analysis...]"
+             ./gradlew sonar -Dsonar.projectKey=JumpingKeyCaps_OCR_Projet17_Rebonnte -Dsonar.organization=jumpingkeycaps -Dsonar.host.url=https://sonarcloud.io -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml --info
 
-      # Step 7 : Vérification du statut du job
-      - name: Fail PR on error
+      # Step  : Construire l'APK de release signé
+      - name: Build release APK
+        run: ./gradlew assembleRelease
+        env:
+           KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
+           KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
+           KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
+
+      # Step  : Sauvegarder l'APK généré
+      - name: Upload APK Artifact
+        uses: actions/upload-artifact@v4
+        with:
+           name: release-apk
+           path: app/build/outputs/apk/release/app-release.apk
+
+      # Step  : No Validation PR en cas d'échec
+      - name: Clearance PR
         if: ${{ failure() }}
-        run: exit 1
+        run: echo "Build ou analyse de qualité échouée, PR bloquée."
